#!/sbin/sh

echo "Memory Manager"
echo ""

cp -fR /sdcard/OpenRecovery/mod/etc/init.d/memory1.sh /system/etc/init.d/99complete


chmod 755 /system/etc/init.d/99complete
chown 0.2000 /system/etc/init.d/99complete


sleep 1
