#!/sbin/sh

echo "Mods Autostart"
echo ""

echo "modifying boot..."

if [ ! -f "/system/bin/mot_boot_mode1" ];
then
	mkdir -p /sdcard/OpenRecovery/backup/bin
	cp -f /system/bin/mot_boot_mode /sdcard/OpenRecovery/backup/bin/mot_boot_mode
	cp -f /system/bin/mot_boot_mode /system/bin/mot_boot_mode1
else
	mkdir -p /sdcard/OpenRecovery/backup/bin
	cp -f /system/bin/mot_boot_mode.bin /sdcard/OpenRecovery/backup/bin/mot_boot_mode
fi
cp -f /sdcard/OpenRecovery/mod/system/bin/mot_boot_mode-22 /system/bin/mot_boot_mode
chmod 755 /system/bin/mot_boot_mo*
chown 0.2000 /system/bin/mot_boot_mo*

sleep 1
