#!/sbin/sh

echo "mod. Overclock Menu" > "$MENU_FILE"
echo "Go Back:menu:.." >> "$MENU_FILE"
echo "Undervolt to 550/400/250/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock550.sh" >> "$MENU_FILE"
echo "Overclock to 650/500/250/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock650.sh" >> "$MENU_FILE"
echo "Overclock to 750/500/250/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock750.sh" >> "$MENU_FILE"
echo "Overclock to 750/600/400/250 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock750-2.sh" >> "$MENU_FILE"
echo "Overclock to 800/600/250/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock800.sh" >> "$MENU_FILE"
echo "Overclock to 800/600/400/250 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock800-2.sh" >> "$MENU_FILE"
echo "Overclock to 900/700/500/250 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock900.sh" >> "$MENU_FILE"
echo "Overclock to 900/600/400/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock900-2.sh" >> "$MENU_FILE"
echo "Overclock to 1000/750/500/250 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock1000.sh" >> "$MENU_FILE"
echo "Overclock to 1000/750/400/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock1000-2.sh" >> "$MENU_FILE"
echo "Overclock to 1100/750/500/250 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock1100.sh" >> "$MENU_FILE"
echo "Overclock to 1100/750/400/125 Mhz:shell:/sdcard/OpenRecovery/mod/scripts/overclock1100-2.sh" >> "$MENU_FILE