#!/system/bin/sh

mountsys
busybox mv /system/media/audio/ui/camera_click.ogg /system/media/audio/ui/camera_click.bak
busybox mv /system/media/audio/ui/VideoRecord.ogg /system/media/audio/ui/VideoRecord.bak
unmountsys
sync
echo 'Camera & Video Recording Sounds Disabled'